name: Auto assign to pull request
on:
  pull_request:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
    - name: Assign
      run: |
        gh pr review --request "realpetrmolek" ${{ github.event.pull_request.html_url }}
      env:
        GH_TOKEN: ${{secrets.GH_TOKEN}}
